image: "rust:latest"

stages:
  - fmt
  - clippy
  - test

fmt:
  stage: fmt
  script:
    - rustc --version && cargo --version
    - cargo fmt --all -- --check

clippy:
  stage: clippy
  script:
    - cargo clippy --all--targets --all-features -- -D warning

test:
  stage: test
  script:
    - cargo test
