image: "rust:latest"

stages:
  - setup
  - fmt
  - clippy
  - test

setup:
  stage: setup
  script:
    - rustup default stable-x86_64-unknown-linux-gnu
    - rustup component add rustfmt
    - rustup component add clippy

fmt:
  stage: fmt
  script:
    - rustc --version && cargo --version
    - cargo fmt --all -- --check

clippy:
  stage: clippy
  script:
    - cargo clippy --all-targets --all-features -- -D warning

test:
  stage: test
  script:
    - cargo test
