image: "rust:latest"

cache:
  paths:
    - $CI_PROJECT_DIR/target

stages:
  - setup
  - fmt
  - lint
  - test

setup:
  stage: setup
  script:
    - rustup default stable-x86_64-unknown-linux-gnu

fmt:
  stage: fmt
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check

clippy:
  stage: lint
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features -- -D warnings

doc:
  stage: lint
  script:
    - rustup component add rustdoc
    - RUSTDOCFLAGS="-Dwarnings" cargo doc --no-deps --all-features

test:
  stage: test
  script:
    - cargo test
