# Replace with your discord bot token.
token = "<YOUR_TOKEN>"
# The logging level.
# Possible options: error, warn, info, debug, trace
# Default value: info
loglevel = "info"
# Admins always have all permissions regardless of server. Some
# commands are only avaliable to admins.
# Note: This feature is only supported if Robbot is compiled with the
# "permissions" feature.
admins = []

# Database
[database]
# Currently only supports myqsl.
driver = "mysql"
host = "127.0.0.1"
port = 3306
user = "robbot"
password = "robbot"
database = "robbot"
