[package]
name = "robbot"
version = "0.1.0"
edition = "2018"

[dependencies]
robbot-derive = { version = "0.1.0", path = "../robbot-derive" }
tokio = "1.12.0"
async-trait = "0.1.51"
serenity = { version = "0.10.8", default-features = false, features = ["builder", "model", "rustls_backend"] }
chrono = "0.4.19"
serde = { version = "1.0.*", features = ["derive"] }
