//! Hooks
//!

pub struct Hook {
    name: String,
    on_event: Event,
}

pub trait EventTrait {
    type Context;
}

pub enum Event {
    ApplicationCommandCreate,
    ApplicationCommandDelete,
    ApplicationCommandUpdate,
    CacheReady,
    CategoryCreate,
    CategoryDelete,
    ChannelCreate,
    ChannelDelete,
    ChannelPinsUpdate,
    Channelupdate,
    GuildBanAddition,
    GuildBanRemoval,
    GuildCreate,
    GuildDelete,
    GuildEmojisUpdate,
    GuildIntegrationsUpdate,
    GuildMemberAddition,
    GuildMemberRemoval,
    GuildMemberUpdate,
    GuildMembersChunk,
    GuildRoleCreate,
    GuildRoleDelete,
    GuildRoleUpdate,
    GuildUnavaliable,
    GuildUpdate,
    IntegrationCreate,
    IntegrationDelete,
    InteractionCreate,
    InviteCreate,
    InviteDelete,
    Message,
    MessageDelete,
    MessageDeleteBulk,
    MessageUpdate,
    PresenceReplace,
    PresenceUpdate,
    ReactionAdd,
    ReactionRemove,
    ReactionRemoveAll,
    Ready,
    Resume,
    SharedStageUpdate,
    StageInstanceCreate,
    StageInstanceDelete,
    StageInstanceUpdate,
    ThreadCreate,
    ThreadDelete,
    ThreadListSync,
    ThreadMemberUpdate,
    ThreadMembersUpdate,
    ThreadUpdate,
    TypingStart,
    Unknown,
    UserUpdate,
    VoiceServerUpdate,
    VoiceStateUpdate,
    WebhookUpdate,
}
